ENVIRONMENT:
  MAX_EPISODE_STEPS: 150
  CURRICULUM: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['DEPTH_SENSOR']
    HEIGHT: 0.60
    RADIUS: 0.3
  HABITAT_SIM_V0:
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 320
    HEIGHT: 240
    HFOV: 70
    ORIENTATION: [-0.7, 0.0, 0.0]
    # ORIENTATION: [0, 0, 0]
    # POSITION: [0, 0.69, -0.1778]
    POSITION: [0.0, 1.1, 1.0]
  DEPTH_SENSOR:
    WIDTH: 320
    HEIGHT: 240
    MAX_DEPTH: 10.0
    MIN_DEPTH: 0.3
    HFOV: 70
    ORIENTATION: [0.0, 0.0, 0.0]
    POSITION: [0.0, 0.0, 0.0]
TASK:
  TYPE: MultiNav-v0
  Z:
    USE_Z: False
    USE_MLP: False
    ADAPT_Z: null
    Z_OUT_DIM: 1
    PREV_WINDOW: 50
    Z_ENC_INPUTS: ['urdf', 'prev_states', 'prev_actions']

  ROBOTS: ['Spot']
#  ROBOT_URDFS: ["/coc/testnvme/jtruong33/data/URDF_demo_assets/a1/a1.urdf"]
  ROBOT_URDFS: ["/coc/testnvme/jtruong33/data/URDF_demo_assets/spot_hybrid_urdf/habitat_spot_urdf/urdf/spot_hybrid.urdf"]

  SUCCESS_DISTANCE: 0.425

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  POSSIBLE_ACTIONS: ["VELOCITY_CONTROL"]
  ACTIONS:
    VELOCITY_CONTROL:
      TIME_STEP: 1.0
      CTRL_FREQ: 240.0
      MUST_CALL_STOP: False
      MIN_ABS_HOR_SPEED: 0.035
      MIN_ABS_LIN_SPEED: 0.035
      MIN_ABS_ANG_SPEED: 1.0
      POLICY_LIN_VEL_RANGE: [-0.50, 0.50]
      POLICY_HOR_VEL_RANGE: [-0.50, 0.50]
      POLICY_ANG_VEL_RANGE: [-17.19, 17.19]
      ROBOT_LIN_VEL_RANGES: [ [ -0.35, 0.35 ] ]
      ROBOT_HOR_VEL_RANGES: [ [ -0.35, 0.35 ] ]
      ROBOT_ANG_VEL_RANGES: [ [ -10.0, 10.0 ] ]

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'EPISODE_DISTANCE', 'SUCCESS', 'SPL', 'COLLISIONS', 'VEL_TRK_ERR']
  SUCCESS:
    SUCCESS_DISTANCE: 0.425

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: /coc/testnvme/jtruong33/data/datasets/pointnav_hm3d_gibson/pointnav_spot_0.3/{split}/{split}.json.gz
